export enum ETableAlign {
  left = 'left',
  right = 'right',
  center = 'center',
}
export enum ETableFilterType {
  search = 'search',
  checkbox = 'checkbox',
  radio = 'radio',
  date = 'date',
}
export enum EFormType {
  onlyNumber = 'only_number',
  hidden = 'hidden',
  number = 'number',
  text = 'text',
  name = 'name',
  tab = 'tab',
  addable = 'addable',
  cascader = 'cascader',
  editor = 'editor',
  upload = 'upload',
  tableTransfer = 'table_transfer',
  password = 'password',
  textarea = 'textarea',
  slider = 'slider',
  sliderNumber = 'slider_number',
  date = 'date',
  dateRange = 'date_range',
  time = 'time',
  timeRange = 'time_range',
  checkbox = 'checkbox',
  radio = 'radio',
  tag = 'tag',
  chips = 'chips',
  select = 'select',
  selectTable = 'select_table',
  treeSelect = 'tree_select',
  otp = 'otp',
  switch = 'switch',
}
export enum EFormModeSelect {
  multiple = 'multiple',
  tags = 'tags',
}
export enum EFormPickerDate {
  time = 'time',
  date = 'date',
  week = 'week',
  month = 'month',
  quarter = 'quarter',
  year = 'year',
}
export enum EFormRuleType {
  required = 'required',
  email = 'email',
  min = 'min',
  max = 'max',
  custom = 'custom',
  phone = 'phone',
  url = 'url',
  onlyText = 'only_text',
  onlyTextSpace = 'only_text_space',
  textarea = 'textarea',
  api = 'api',
}
export enum EStatusState {
  idle = 'idle',
  getPending = 'get.pending',
  getFulfilled = 'get.fulfilled',
  getRejected = 'get.rejected',
  getByIdPending = 'getById.pending',
  getByIdFulfilled = 'getById.fulfilled',
  getByIdRejected = 'getById.rejected',
  postPending = 'post.pending',
  postFulfilled = 'post.fulfilled',
  postRejected = 'post.rejected',
  putPending = 'put.pending',
  putFulfilled = 'put.fulfilled',
  putRejected = 'put.rejected',
  deletePending = 'delete.pending',
  deleteFulfilled = 'delete.fulfilled',
  deleteRejected = 'delete.rejected',
}
export enum ETypeChart {
  pie = 'pie',
  ring = 'ring',
  bubble = 'bubble',
  line = 'line',
  bar = 'bar',
  stackedBar = 'stacked-bar',
  lineBar = 'line-bar',
  area = 'area',
  stackedArea = 'stacked-area',
  scatter = 'scatter',
}
