name: "laravel-react"
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        image: bca32d67aa5336a0b50e59b948e308ab50377805fd9bd24529504d85366b78a4
        ports:
            - 8000:8000
        volumes:
            - .:/app
            - /app/vendor
        depends_on:
            - db

    db:
        image: mariadb:10.8.3
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: laravel-react
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
