name: "laravel-react"
services:
  db:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: laravel-react
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3366:3306

  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: f08bc222baa618ff8eaaf6f9c84575aa083a1bb5e04fc4879921cc1fe2c0c697
    ports:
      - 3000:3000
    volumes:
      - ..:/app
      - /app/vendor
    depends_on:
      - db
    command: php artisan serve --host 0.0.0.0 --port=3000
