version: "3.9"
services:
  db:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: laravel-react
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3366:3306

  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile-build
      args:
        - PROD=false
    environment:
      HOST_ADDRESS: "http://localhost:3000/administrator"
      REDIS_HOST: "cache"
      BROWSER_TIMEOUT: "4"
      HEADLESS: "True"
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ../output:/app/e2e/result
    command: php artisan serve --host 0.0.0.0 --port=3000
