FROM bitnami/node:20 as build-client
WORKDIR /app
COPY --chown=root:root ../client .
RUN npm install -f && \
npm run build:prod

FROM php:8.3-fpm-alpine

RUN docker-php-ext-install pdo pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin --filename=composer

WORKDIR /app
COPY .. .
RUN rm -rf /app/client
COPY --from=build-client /app/build/. ./public/.
RUN rm -rf /app/public/index.html
COPY --from=build-client /app/build/index.html ./resources/views/administrator.blade.php
COPY --chown=root:root ../.env.example ./.env
RUN composer install

ARG PROD=false
COPY --chown=root:root ../client/test ./robot
RUN  if [ "$PROD" = "false" ] ; then install_packages python3; fi
RUN  if [ "$PROD" = "false" ] ; then ln -sf python3 /usr/bin/python && \
pip3 install --no-cache -r /robot/requirements.txt && \
npx playwright install-deps; fi
RUN  if [ "$PROD" = "false" ] ; then rfbrowser init; fi

CMD php artisan key:generate && php artisan storage:link
