FROM bitnami/node:20 as build-client
WORKDIR /app
COPY --chown=root:root ../client .
RUN npm install -f && \
npm run build:prod

FROM ubuntu:latest

RUN  apt-get update -y
RUN  apt-get install php php-curl curl php-mysql php-sqlite3 libapache2-mod-php php-mbstring php-xmlrpc php-soap php-gd php-xml php-cli php-zip php-bcmath php-tokenizer php-json php-pear -y
RUN curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin --filename=composer

WORKDIR /app
COPY .. .
RUN rm -rf /app/client
COPY --from=build-client /app/build/. ./public/.
RUN rm -rf /app/public/index.html
COPY --from=build-client /app/build/index.html ./resources/views/administrator.blade.php
COPY --chown=root:root ../.env.example ./.env
RUN composer install

ARG PROD=false
COPY --chown=root:root ../client/e2e ./e2e
RUN  if [ "$PROD" = "false" ] ; then apt-get install -y python3 python3-pip nodejs npm; fi
RUN  if [ "$PROD" = "false" ] ; then npx playwright install-deps; fi
RUN  if [ "$PROD" = "false" ] ; then pip3 install --no-cache --break-system-packages -r ./e2e/requirements.txt; fi
RUN  if [ "$PROD" = "false" ] ; then rfbrowser init; fi

CMD php artisan key:generate && php artisan storage:link
