---
name: Checks

on:
  push:
    branches: ["master"]
  pull_request:
    branches:
      - "master"
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run actions/checkout@v2
        uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose -f docker/docker-test.yml up -d
      - name: Run Test Backend
        run: docker-compose -f docker/docker-test.yml exec -T server ./vendor/bin/phpunit
      - name: Run Clear config
        if: ${{ !cancelled() }}
        run: docker-compose -f docker/docker-test.yml exec -T server php artisan config:clear
      - name: Generate key
        if: ${{ !cancelled() }}
        run: docker-compose -f docker/docker-test.yml exec -T server php artisan key:generate
      - name: Wait for MySQL to initialize
        if: ${{ !cancelled() }}
        run: sleep 1
      - name: Run Migration && Seed Database
        if: ${{ !cancelled() }}
        run: docker-compose -f docker/docker-test.yml exec -T server php artisan migrate:refresh --seed
      - name: Run Test Frontend
        if: ${{ !cancelled() }}
        run: docker-compose -f docker/docker-test.yml exec -T server robot -i Develop -d e2e/result e2e/testcases/*.robot
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: output
          path: output/
          retention-days: 30
#       docker-compose -f docker/docker-build.yml up -d --build
#       docker-compose -f docker/docker-build.yml run --rm server sh -c "npm run migration && npm run seed"
